// <auto-generated/>
using FairPlayTube.ClientServices.KiotaClient.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace FairPlayTube.ClientServices.KiotaClient.Videoinfo.GetPaginatedCompletedVideoInfoAsync {
    /// <summary>
    /// Builds and executes requests for operations under \videoinfo\GetPaginatedCompletedVideoInfoAsync
    /// </summary>
    public class GetPaginatedCompletedVideoInfoAsyncRequestBuilder : BaseRequestBuilder {
        /// <summary>
        /// Instantiates a new GetPaginatedCompletedVideoInfoAsyncRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetPaginatedCompletedVideoInfoAsyncRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/videoinfo/GetPaginatedCompletedVideoInfoAsync{?startIndex*}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new GetPaginatedCompletedVideoInfoAsyncRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetPaginatedCompletedVideoInfoAsyncRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/videoinfo/GetPaginatedCompletedVideoInfoAsync{?startIndex*}", rawUrl) {
        }
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<VideoInfoModelPaginationOfT?> GetAsync(Action<GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetRequestConfiguration>? requestConfiguration = default, CancellationToken cancellationToken = default) {
#nullable restore
#else
        public async Task<VideoInfoModelPaginationOfT> GetAsync(Action<GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetRequestConfiguration> requestConfiguration = default, CancellationToken cancellationToken = default) {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<VideoInfoModelPaginationOfT>(requestInfo, VideoInfoModelPaginationOfT.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetRequestConfiguration>? requestConfiguration = default) {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetRequestConfiguration> requestConfiguration = default) {
#endif
            var requestInfo = new RequestInformation {
                HttpMethod = Method.GET,
                UrlTemplate = UrlTemplate,
                PathParameters = PathParameters,
            };
            if (requestConfiguration != null) {
                var requestConfig = new GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetRequestConfiguration();
                requestConfiguration.Invoke(requestConfig);
                requestInfo.AddQueryParameters(requestConfig.QueryParameters);
                requestInfo.AddRequestOptions(requestConfig.Options);
                requestInfo.AddHeaders(requestConfig.Headers);
            }
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public GetPaginatedCompletedVideoInfoAsyncRequestBuilder WithUrl(string rawUrl) {
            return new GetPaginatedCompletedVideoInfoAsyncRequestBuilder(rawUrl, RequestAdapter);
        }
        public class GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetQueryParameters {
            [QueryParameter("startIndex")]
            public int? StartIndex { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        public class GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetRequestConfiguration {
            /// <summary>Request headers</summary>
            public RequestHeaders Headers { get; set; }
            /// <summary>Request options</summary>
            public IList<IRequestOption> Options { get; set; }
            /// <summary>Request query parameters</summary>
            public GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetQueryParameters QueryParameters { get; set; } = new GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetQueryParameters();
            /// <summary>
            /// Instantiates a new GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetRequestConfiguration and sets the default values.
            /// </summary>
            public GetPaginatedCompletedVideoInfoAsyncRequestBuilderGetRequestConfiguration() {
                Options = new List<IRequestOption>();
                Headers = new RequestHeaders();
            }
        }
    }
}
