// <auto-generated/>
using FairPlayTube.ClientServices.KiotaClient.Identity.GetMyRoles;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace FairPlayTube.ClientServices.KiotaClient.Identity {
    /// <summary>
    /// Builds and executes requests for operations under \identity
    /// </summary>
    public class IdentityRequestBuilder : BaseRequestBuilder {
        /// <summary>The GetMyRoles property</summary>
        public GetMyRolesRequestBuilder GetMyRoles { get =>
            new GetMyRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new IdentityRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new IdentityRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity", rawUrl) {
        }
    }
}
