// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;

[Table("MonthlyBudgetInfo", Schema = "FairPlayBudget")]
[Index("Description", Name = "UI_MonthlyBudgetInfo_Description", IsUnique = true)]
public partial class MonthlyBudgetInfo
{
    [Key]
    public long MonthlyBudgetInfoId { get; set; }

    [Required]
    [StringLength(150)]
    public string Description { get; set; }

    [Required]
    [StringLength(450)]
    public string OwnerId { get; set; }

    [InverseProperty("MonthlyBudgetInfo")]
    public virtual ICollection<Expense> Expense { get; set; } = new List<Expense>();

    [InverseProperty("MonthlyBudgetInfo")]
    public virtual ICollection<Income> Income { get; set; } = new List<Income>();

    [ForeignKey("OwnerId")]
    [InverseProperty("MonthlyBudgetInfo")]
    public virtual AspNetUsers Owner { get; set; }
}