// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;

[Keyless]
public partial class VwBalance
{
    [Required]
    [StringLength(450)]
    public string OwnerId { get; set; }

    [Column(TypeName = "money")]
    public decimal Amount { get; set; }

    public DateTimeOffset DateTime { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    public int CurrencyId { get; set; }

    [Required]
    [StringLength(50)]
    public string Currency { get; set; }

    [Required]
    [StringLength(150)]
    public string MonthlyBudgetDescription { get; set; }
}