// <auto-generated/>
using FairPlayTube.ClientServices.KiotaClient.Api.Photo.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace FairPlayTube.ClientServices.KiotaClient.Api.Photo {
    /// <summary>
    /// Builds and executes requests for operations under \api\photo
    /// </summary>
    public class PhotoRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the FairPlayTube.ClientServices.KiotaClient.api.photo.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithPhotoItemRequestBuilder this[long position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("photoId", position);
            return new WithPhotoItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>Gets an item from the FairPlayTube.ClientServices.KiotaClient.api.photo.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public WithPhotoItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("photoId", position);
            return new WithPhotoItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new PhotoRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhotoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/photo", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new PhotoRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhotoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/photo", rawUrl) {
        }
    }
}
