CREATE TABLE [dbo].[Photo]
(
	[PhotoId] BIGINT NOT NULL CONSTRAINT PK_Photo PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Filename] NVARCHAR(50) NOT NULL, 
    [PhotoBytes] VARBINARY(MAX) NOT NULL
)