// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;

[Table("ApplicationUserVouch", Schema = "FairPlayDating")]
[Index("FromApplicationUserId", "ToApplicationUserId", Name = "UI_ApplicationUserVouch_FromApplicationUserId_ToApplicationUserId", IsUnique = true)]
public partial class ApplicationUserVouch
{
    [Key]
    public long ApplicationUserVouchId { get; set; }

    [Required]
    public string FromApplicationUserId { get; set; }

    [Required]
    public string ToApplicationUserId { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    [ForeignKey("FromApplicationUserId")]
    [InverseProperty("ApplicationUserVouchFromApplicationUser")]
    public virtual AspNetUsers FromApplicationUser { get; set; }

    [ForeignKey("ToApplicationUserId")]
    [InverseProperty("ApplicationUserVouchToApplicationUser")]
    public virtual AspNetUsers ToApplicationUser { get; set; }
}