// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;

[Table("EyesColor", Schema = "FairPlayDating")]
public partial class EyesColor
{
    [Key]
    public int EyesColorId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("EyesColor")]
    public virtual ICollection<UserProfile> UserProfileEyesColor { get; set; } = new List<UserProfile>();

    [InverseProperty("PreferredEyesColor")]
    public virtual ICollection<UserProfile> UserProfilePreferredEyesColor { get; set; } = new List<UserProfile>();
}