// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;

[Table("NotLikedUserProfile", Schema = "FairPlayDating")]
[Index("NotLikingApplicationUserId", "NotLikedApplicationUserId", Name = "UI_NotLikedUserProfile_NotLikingApplicationUserId_NotLikedApplicationUserId", IsUnique = true)]
public partial class NotLikedUserProfile
{
    [Key]
    public long NotLikedUserProfileId { get; set; }

    [Required]
    public string NotLikingApplicationUserId { get; set; }

    [Required]
    public string NotLikedApplicationUserId { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    [ForeignKey("NotLikedApplicationUserId")]
    [InverseProperty("NotLikedUserProfileNotLikedApplicationUser")]
    public virtual AspNetUsers NotLikedApplicationUser { get; set; }

    [ForeignKey("NotLikingApplicationUserId")]
    [InverseProperty("NotLikedUserProfileNotLikingApplicationUser")]
    public virtual AspNetUsers NotLikingApplicationUser { get; set; }
}