// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;

[Table("UserActivity", Schema = "FairPlayDating")]
[Index("ApplicationUserId", "ActivityId", Name = "UI_UserActivity_ApplicationUserId_ActivityId", IsUnique = true)]
public partial class UserActivity
{
    [Key]
    public long UserActivityId { get; set; }

    [Required]
    public string ApplicationUserId { get; set; }

    public short ActivityId { get; set; }

    public short FrequencyId { get; set; }

    [ForeignKey("ActivityId")]
    [InverseProperty("UserActivity")]
    public virtual Activity Activity { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("UserActivity")]
    public virtual AspNetUsers ApplicationUser { get; set; }

    [ForeignKey("FrequencyId")]
    [InverseProperty("UserActivity")]
    public virtual Frequency Frequency { get; set; }
}