// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.dboSchema;

[Index("StateOrProvinceId", "Name", Name = "UI_City_Name", IsUnique = true)]
public partial class City
{
    [Key]
    public int CityId { get; set; }

    [Required]
    [StringLength(500)]
    public string Name { get; set; }

    public int StateOrProvinceId { get; set; }

    [ForeignKey("StateOrProvinceId")]
    [InverseProperty("City")]
    public virtual StateOrProvince StateOrProvince { get; set; }
}