// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.dboSchema;

public partial class LinkedInConnection
{
    [Key]
    public long LinkedInConnectionId { get; set; }

    [Required]
    [StringLength(450)]
    public string ApplicationUserId { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(1000)]
    public string ProfileUrl { get; set; }

    [StringLength(50)]
    public string EmailAddress { get; set; }

    [StringLength(1000)]
    public string Company { get; set; }

    [StringLength(1000)]
    public string Position { get; set; }

    public DateOnly ConnectedOn { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("LinkedInConnection")]
    public virtual AspNetUsers ApplicationUser { get; set; }
}