// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.dboSchema;

public partial class Photo
{
    [Key]
    public long PhotoId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string Filename { get; set; }

    [Required]
    public byte[] PhotoBytes { get; set; }

    [InverseProperty("Photo")]
    public virtual ICollection<Post> Post { get; set; } = new List<Post>();

    [InverseProperty("ThumbnailPhoto")]
    public virtual ICollection<Product> Product { get; set; } = new List<Product>();

    [InverseProperty("ProfilePhoto")]
    public virtual ICollection<UserProfile> UserProfile { get; set; } = new List<UserProfile>();

    [InverseProperty("VideoThumbnailPhoto")]
    public virtual ICollection<VideoInfo> VideoInfo { get; set; } = new List<VideoInfo>();
}