// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.dboSchema;

[Index("PromptName", Name = "UI_Prompt_PromptName", IsUnique = true)]
public partial class Prompt
{
    [Key]
    public int PromptId { get; set; }

    [Required]
    [StringLength(100)]
    public string PromptName { get; set; }

    [Required]
    public string BaseText { get; set; }

    [InverseProperty("Prompt")]
    public virtual ICollection<PromptVariable> PromptVariable { get; set; } = new List<PromptVariable>();
}