// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.dboSchema;

[Index("PromptId", "VariableName", Name = "UI_PromptVariable_PromptId_VariableName", IsUnique = true)]
public partial class PromptVariable
{
    [Key]
    public int PromptVariableId { get; set; }

    public int PromptId { get; set; }

    [Required]
    [StringLength(50)]
    public string VariableName { get; set; }

    [ForeignKey("PromptId")]
    [InverseProperty("PromptVariable")]
    public virtual Prompt Prompt { get; set; }
}