// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.dboSchema;

[Index("ApplicationUserId", Name = "UI_UserFunds_ApplicationUserId", IsUnique = true)]
public partial class UserFunds
{
    [Key]
    [Column("UserFunds")]
    public long UserFunds1 { get; set; }

    [Required]
    public string ApplicationUserId { get; set; }

    [Column(TypeName = "money")]
    public decimal AvailableFunds { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("UserFunds")]
    public virtual AspNetUsers ApplicationUser { get; set; }
}