// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.dboSchema;

[Index("VideoInfoId", Name = "IX_VisitorTracking_VideoId")]
public partial class VisitorTracking
{
    [Key]
    public long VisitorTrackingId { get; set; }

    [StringLength(450)]
    public string ApplicationUserId { get; set; }

    [Required]
    [StringLength(250)]
    public string RemoteIpAddress { get; set; }

    [Required]
    [StringLength(250)]
    public string Country { get; set; }

    public DateTimeOffset VisitDateTime { get; set; }

    [Required]
    public string UserAgent { get; set; }

    [Required]
    public string Host { get; set; }

    [Required]
    public string VisitedUrl { get; set; }

    public long? VideoInfoId { get; set; }

    public Guid? SessionId { get; set; }

    public DateTimeOffset? LastTrackedDateTime { get; set; }

    public string Referer { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("VisitorTracking")]
    public virtual AspNetUsers ApplicationUser { get; set; }

    [ForeignKey("VideoInfoId")]
    [InverseProperty("VisitorTracking")]
    public virtual VideoInfo VideoInfo { get; set; }
}