// <auto-generated/>
using FairPlayTube.ClientServices.KiotaClient.Account.Manage.DownloadPersonalData;
using FairPlayTube.ClientServices.KiotaClient.Account.Manage.LinkExternalLogin;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace FairPlayTube.ClientServices.KiotaClient.Account.Manage {
    /// <summary>
    /// Builds and executes requests for operations under \Account\Manage
    /// </summary>
    public class ManageRequestBuilder : BaseRequestBuilder {
        /// <summary>The DownloadPersonalData property</summary>
        public DownloadPersonalDataRequestBuilder DownloadPersonalData { get =>
            new DownloadPersonalDataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The LinkExternalLogin property</summary>
        public LinkExternalLoginRequestBuilder LinkExternalLogin { get =>
            new LinkExternalLoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new ManageRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ManageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account/Manage", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new ManageRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ManageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account/Manage", rawUrl) {
        }
    }
}
