CREATE TABLE [FairPlaySocial].[Post]
(
	[PostId] BIGINT NOT NULL CONSTRAINT PK_Post PRIMARY KEY IDENTITY, 
    [PostVisibilityId] INT NOT NULL DEFAULT 1, 
    [PhotoId] BIGINT NULL,
    [PostTypeId] INT NOT NULL DEFAULT 1, 
    [ReplyToPostId] BIGINT NULL,
    [GroupId] BIGINT NULL,
    [Text] NVARCHAR(500) NOT NULL,
    [OwnerApplicationUserId] NVARCHAR(450) NOT NULL, 
    [RowCreationDateTime] DATETIMEOFFSET NOT NULL, 
    [RowCreationUser] NVARCHAR(256) NOT NULL,
    [SourceApplication] NVARCHAR(250) NOT NULL, 
    [OriginatorIPAddress] NVARCHAR(100) NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),
    [CreatedFromPostId] BIGINT NULL, 
    [CreatedAtLatitude] FLOAT NULL, 
    [CreatedAtLongitude] FLOAT NULL, 
    [CreatedAtGeoLocation] [sys].[geography] NULL, 
    [RootPostId] BIGINT NULL, 
    CONSTRAINT [FK_Post_ApplicationUser] FOREIGN KEY ([OwnerApplicationUserId]) REFERENCES [dbo].[AspNetUsers]([Id]),  
    CONSTRAINT [FK_Post_Photo] FOREIGN KEY ([PhotoId]) REFERENCES [Photo]([PhotoId]), 
    CONSTRAINT [FK_Post_PostVisibility] FOREIGN KEY ([PostVisibilityId]) REFERENCES [FairPlaySocial].[PostVisibility]([PostVisibilityId]), 
    CONSTRAINT [FK_Post_Post] FOREIGN KEY ([CreatedFromPostId]) REFERENCES [FairPlaySocial].[Post]([PostId]), 
    CONSTRAINT [FK_Post_Post_ReplyToPostId] FOREIGN KEY ([ReplyToPostId]) REFERENCES [FairPlaySocial].[Post]([PostId]), 
    CONSTRAINT [FK_Post_PostType] FOREIGN KEY ([PostTypeId]) REFERENCES [FairPlaySocial].[PostType]([PostTypeId]), 
    CONSTRAINT [FK_Post_Post_RootPost] FOREIGN KEY ([RootPostId]) REFERENCES [FairPlaySocial].[Post]([PostId]), 
    CONSTRAINT [FK_Post_Group] FOREIGN KEY ([GroupId]) REFERENCES [FairPlaySocial].[Group]([GroupId])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = FairPlaySocial.PostHistory))