// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;

[Table("NewVideoRecommendation", Schema = "FairPlayTube")]
public partial class NewVideoRecommendation
{
    [Key]
    public long NewVideoRecommendationId { get; set; }

    [Required]
    [StringLength(450)]
    public string ApplicationUserId { get; set; }

    [Required]
    public string HtmlNewVideoRecommendation { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("NewVideoRecommendation")]
    public virtual AspNetUsers ApplicationUser { get; set; }
}