// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;

[Table("VideoIndexerSupportedLanguage", Schema = "FairPlayTube")]
[Index("LanguageCode", Name = "UI_VideoIndexerSupportedLanguage_LanguageCode", IsUnique = true)]
[Index("Name", Name = "UI_VideoIndexerSupportedLanguage_Name", IsUnique = true)]
public partial class VideoIndexerSupportedLanguage
{
    [Key]
    public int VideoIndexerSupportedLanguageId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(10)]
    public string LanguageCode { get; set; }
}