// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;

[Table("VideoTopic", Schema = "FairPlayTube")]
[Index("VideoInfoId", "Topic", Name = "UI_VideoTopic_VideoInfoId_Topic", IsUnique = true)]
public partial class VideoTopic
{
    [Key]
    public long VideoTopicId { get; set; }

    public long VideoInfoId { get; set; }

    [Required]
    [StringLength(500)]
    public string Topic { get; set; }

    public double Confidence { get; set; }

    [ForeignKey("VideoInfoId")]
    [InverseProperty("VideoTopic")]
    public virtual VideoInfo VideoInfo { get; set; }
}