// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;

[Table("VideoCaptions", Schema = "FairPlayTube")]
public partial class VideoCaptions
{
    [Key]
    public long VideoCaptionsId { get; set; }

    public long VideoInfoId { get; set; }

    [Required]
    public string Content { get; set; }

    [Required]
    [StringLength(10)]
    public string Language { get; set; }

    [ForeignKey("VideoInfoId")]
    [InverseProperty("VideoCaptions")]
    public virtual VideoInfo VideoInfo { get; set; }
}