// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;

[Table("VideoKeyword", Schema = "FairPlayTube")]
[Index("VideoInfoId", "Keyword", Name = "UI_VideoKeyword_VideoInfoId_Keyword", IsUnique = true)]
public partial class VideoKeyword
{
    [Key]
    public long VideoKeywordId { get; set; }

    public long VideoInfoId { get; set; }

    [Required]
    [StringLength(500)]
    public string Keyword { get; set; }

    [ForeignKey("VideoInfoId")]
    [InverseProperty("VideoKeyword")]
    public virtual VideoInfo VideoInfo { get; set; }
}