// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;

[Table("VideoPassiveIncome", Schema = "FairPlayTube")]
public partial class VideoPassiveIncome
{
    [Key]
    public long VideoPassiveIncomeIdeaId { get; set; }

    public long VideoInfoId { get; set; }

    [Required]
    public string HtmlPassiveIncomeIdea { get; set; }

    [Column("OpenAIPromptId")]
    public long OpenAipromptId { get; set; }

    [ForeignKey("OpenAipromptId")]
    [InverseProperty("VideoPassiveIncome")]
    public virtual OpenAiprompt OpenAiprompt { get; set; }

    [ForeignKey("VideoInfoId")]
    [InverseProperty("VideoPassiveIncome")]
    public virtual VideoInfo VideoInfo { get; set; }
}