// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayShopSchema;

[Table("Product", Schema = "FairPlayShop")]
[Index("Name", "OwnerId", Name = "UI_Product_Name", IsUnique = true)]
public partial class Product
{
    [Key]
    public long ProductId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    public int QuantityInStock { get; set; }

    public byte ProductStatusId { get; set; }

    [Required]
    public string OwnerId { get; set; }

    [Column(TypeName = "money")]
    public decimal SellingPrice { get; set; }

    [Column(TypeName = "money")]
    public decimal AcquisitionCost { get; set; }

    [Required]
    [Column("SKU")]
    [StringLength(50)]
    public string Sku { get; set; }

    [StringLength(50)]
    public string Barcode { get; set; }

    public long ThumbnailPhotoId { get; set; }

    public long StoreId { get; set; }

    [ForeignKey("OwnerId")]
    [InverseProperty("Product")]
    public virtual AspNetUsers Owner { get; set; }

    [ForeignKey("ProductStatusId")]
    [InverseProperty("Product")]
    public virtual ProductStatus ProductStatus { get; set; }

    [ForeignKey("StoreId")]
    [InverseProperty("Product")]
    public virtual Store Store { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<StoreCustomerOrderDetail> StoreCustomerOrderDetail { get; set; } = new List<StoreCustomerOrderDetail>();

    [ForeignKey("ThumbnailPhotoId")]
    [InverseProperty("Product")]
    public virtual Photo ThumbnailPhoto { get; set; }
}