// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayShopSchema;

[Table("StoreCustomerOrderDetail", Schema = "FairPlayShop")]
public partial class StoreCustomerOrderDetail
{
    [Key]
    [Column("StoreCustomerOrderDetail")]
    public long StoreCustomerOrderDetail1 { get; set; }

    public long StoreCustomerOrderId { get; set; }

    public long ProductId { get; set; }

    [Column(TypeName = "money")]
    public decimal UnityPrice { get; set; }

    [Column(TypeName = "money")]
    public decimal Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal LineTotal { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("StoreCustomerOrderDetail")]
    public virtual Product Product { get; set; }

    [ForeignKey("StoreCustomerOrderId")]
    [InverseProperty("StoreCustomerOrderDetail")]
    public virtual StoreCustomerOrder StoreCustomerOrder { get; set; }
}