// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayShopSchema;

[Table("StoreCustomer", Schema = "FairPlayShop")]
public partial class StoreCustomer
{
    [Key]
    public long StoreCustomerId { get; set; }

    public long StoreId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstSurname { get; set; }

    [Required]
    [StringLength(50)]
    public string SecondSurname { get; set; }

    [Required]
    [StringLength(50)]
    public string EmailAddress { get; set; }

    [Required]
    [StringLength(50)]
    public string PhoneNumber { get; set; }

    [ForeignKey("StoreId")]
    [InverseProperty("StoreCustomer")]
    public virtual Store Store { get; set; }

    [InverseProperty("StoreCustomer")]
    public virtual ICollection<StoreCustomerOrder> StoreCustomerOrder { get; set; } = new List<StoreCustomerOrder>();
}