// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayShopSchema;

[Table("Store", Schema = "FairPlayShop")]
public partial class Store
{
    [Key]
    public long StoreId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(450)]
    public string OwnerId { get; set; }

    [ForeignKey("OwnerId")]
    [InverseProperty("Store")]
    public virtual AspNetUsers Owner { get; set; }

    [InverseProperty("Store")]
    public virtual ICollection<Product> Product { get; set; } = new List<Product>();

    [InverseProperty("Store")]
    public virtual ICollection<StoreCustomer> StoreCustomer { get; set; } = new List<StoreCustomer>();
}