// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;

[Table("BlogPost", Schema = "FairPlayBlogs")]
public partial class BlogPost
{
    [Key]
    public long BlogPostId { get; set; }

    public long BlogId { get; set; }

    [Required]
    [StringLength(50)]
    public string Title { get; set; }

    [Required]
    [StringLength(250)]
    public string PreviewText { get; set; }

    [Required]
    public string Content { get; set; }

    public long ThumbnailPhotoId { get; set; }

    public byte BlogPostStatusId { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    [ForeignKey("BlogId")]
    [InverseProperty("BlogPost")]
    public virtual Blog Blog { get; set; }

    [ForeignKey("BlogPostStatusId")]
    [InverseProperty("BlogPost")]
    public virtual BlogPostStatus BlogPostStatus { get; set; }

    [ForeignKey("ThumbnailPhotoId")]
    [InverseProperty("BlogPost")]
    public virtual Photo ThumbnailPhoto { get; set; }
}