// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;

[Table("BlogPostStatus", Schema = "FairPlayBlogs")]
[Index("Name", Name = "UI_BlogPostStatus_Name", IsUnique = true)]
public partial class BlogPostStatus
{
    [Key]
    public int BlogPostStatusId { get; set; }

    [Required]
    [StringLength(10)]
    public string Name { get; set; }

    [InverseProperty("BlogPostStatus")]
    public virtual ICollection<BlogPost> BlogPost { get; set; } = new List<BlogPost>();
}