// <auto-generated/>
using FairPlayTube.ClientServices.KiotaClient.Api.Video.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace FairPlayTube.ClientServices.KiotaClient.Api.Video {
    /// <summary>
    /// Builds and executes requests for operations under \api\video
    /// </summary>
    public class VideoRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the FairPlayTube.ClientServices.KiotaClient.api.video.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithVideoItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("videoId", position);
            return new WithVideoItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new VideoRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/video", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new VideoRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/video", rawUrl) {
        }
    }
}
