BEGIN TRANSACTION
DECLARE @ADMIN_ROLE_NAME NVARCHAR(256) = 'SystemAdmin'
DECLARE @USER_ROLE_NAME NVARCHAR(256) = 'User'
DECLARE @BASICPLANUSER_ROLE_NAME NVARCHAR(256) = 'BasicPlanUser'
--START OF DEFAULT ROLES
IF NOT EXISTS(SELECT * FROM AspNetRoles WHERE Name = @ADMIN_ROLE_NAME)
BEGIN
    INSERT INTO AspNetRoles(Id, [Name], NormalizedName) 
    VALUES (NEWID(), @ADMIN_ROLE_NAME, @ADMIN_ROLE_NAME)
END
IF NOT EXISTS(SELECT * FROM AspNetRoles WHERE Name = @USER_ROLE_NAME)
BEGIN
    INSERT INTO AspNetRoles(Id, [Name], NormalizedName) 
    VALUES (NEWID(), @USER_ROLE_NAME, @USER_ROLE_NAME)
END
IF NOT EXISTS(SELECT * FROM AspNetRoles WHERE Name = @BASICPLANUSER_ROLE_NAME)
BEGIN
    INSERT INTO AspNetRoles(Id, [Name], NormalizedName) 
    VALUES (NEWID(), @BASICPLANUSER_ROLE_NAME, @BASICPLANUSER_ROLE_NAME)
END
--END OF DEFAULT ROLES
--START OF DEFAULT CULTURES
SET IDENTITY_INSERT [dbo].[Culture] ON
DECLARE @CULTURE NVARCHAR(50) = 'en-US'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(1, @CULTURE)
END
SET @CULTURE='es-CR'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(2, @CULTURE)
END
SET @CULTURE='fr-CA'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(3, @CULTURE)
END
SET @CULTURE='it'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(4, @CULTURE)
END
SET @CULTURE='pt-BR'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(5, @CULTURE)
END
SET @CULTURE='la-VA'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(6, @CULTURE)
END
SET IDENTITY_INSERT [dbo].[Culture] OFF
--END OF DEFAULT CULTURES
--IORIGINATOR INFO
DECLARE @ORIGINATORIPADDRESS NVARCHAR(100) = CONVERT(NVARCHAR(100), ISNULL(CONNECTIONPROPERTY('client_net_address'), ''))
DECLARE @SOURCEAPPLICATION NVARCHAR(250) = APP_NAME()
DECLARE @ROWCREATIONUSER NVARCHAR(256) = 'Post Deployment Script'
--START OF DEFAULT IMAGE STYLES
SET IDENTITY_INSERT [dbo].[ImageStyle] ON;
MERGE INTO [dbo].[ImageStyle] AS Target
USING (VALUES
    (1, 'NoPreference', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (2, 'PhotoRealistic', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (3, 'Cartoonish', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (4, 'Abstract', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (5, 'Minimalist', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (6, 'Vintage', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (7, 'Surreal', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (8, 'Watercolor', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (9, 'LineArt', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (10, 'Sketch', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (11, 'PopArt', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (12, 'Retro', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (13, 'Fantasy', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (14, 'Steampunk', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (15, 'PixelArt', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (16, 'Graffiti', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (17, 'Impressionist', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (18, 'ThreeDRendered', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (19, 'Anime', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (20, 'Manga', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (21, 'Gothic', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (22, 'Cyberpunk', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS),
    (23, 'LEGOMinifigures', SYSDATETIMEOFFSET(), @ROWCREATIONUSER, @SOURCEAPPLICATION, @ORIGINATORIPADDRESS)
) AS Source ([ImageStyleId], [StyleName], [RowCreationDateTime], [RowCreationUser], [SourceApplication], [OriginatorIPAddress])
ON Target.[ImageStyleId] = Source.[ImageStyleId]
WHEN MATCHED THEN 
    UPDATE SET 
        [StyleName] = Source.[StyleName],
        [RowCreationDateTime] = Source.[RowCreationDateTime],
        [RowCreationUser] = Source.[RowCreationUser],
        [SourceApplication] = Source.[SourceApplication],
        [OriginatorIPAddress] = Source.[OriginatorIPAddress]
WHEN NOT MATCHED BY TARGET THEN
    INSERT ([ImageStyleId], [StyleName], [RowCreationDateTime], [RowCreationUser], [SourceApplication], [OriginatorIPAddress])
    VALUES (Source.[ImageStyleId], Source.[StyleName], Source.[RowCreationDateTime], Source.[RowCreationUser], Source.[SourceApplication], Source.[OriginatorIPAddress]);

-- Set identity insert OFF
SET IDENTITY_INSERT [dbo].[ImageStyle] OFF;
--END OF DEFAULT IMAGE STYLES
COMMIT