BEGIN TRANSACTION
DECLARE @ADMIN_ROLE_NAME NVARCHAR(256) = 'SystemAdmin'
DECLARE @USER_ROLE_NAME NVARCHAR(256) = 'User'
DECLARE @BASICPLANUSER_ROLE_NAME NVARCHAR(256) = 'BasicPlanUser'
--START OF DEFAULT ROLES
IF NOT EXISTS(SELECT * FROM AspNetRoles WHERE Name = @ADMIN_ROLE_NAME)
BEGIN
    INSERT INTO AspNetRoles(Id, [Name], NormalizedName) 
    VALUES (NEWID(), @ADMIN_ROLE_NAME, @ADMIN_ROLE_NAME)
END
IF NOT EXISTS(SELECT * FROM AspNetRoles WHERE Name = @USER_ROLE_NAME)
BEGIN
    INSERT INTO AspNetRoles(Id, [Name], NormalizedName) 
    VALUES (NEWID(), @USER_ROLE_NAME, @USER_ROLE_NAME)
END
IF NOT EXISTS(SELECT * FROM AspNetRoles WHERE Name = @BASICPLANUSER_ROLE_NAME)
BEGIN
    INSERT INTO AspNetRoles(Id, [Name], NormalizedName) 
    VALUES (NEWID(), @BASICPLANUSER_ROLE_NAME, @BASICPLANUSER_ROLE_NAME)
END
--END OF DEFAULT ROLES
--START OF DEFAULT CULTURES
SET IDENTITY_INSERT [dbo].[Culture] ON
DECLARE @CULTURE NVARCHAR(50) = 'en-US'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(1, @CULTURE)
END
SET @CULTURE='es-CR'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(2, @CULTURE)
END
SET @CULTURE='fr-CA'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(3, @CULTURE)
END
SET @CULTURE='it'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(4, @CULTURE)
END
SET @CULTURE='pt-BR'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(5, @CULTURE)
END
SET @CULTURE='la-VA'
IF NOT EXISTS (SELECT * FROM [dbo].[Culture] WHERE [Name] = @CULTURE)
BEGIN
    INSERT INTO Culture([CultureId],[Name]) VALUES(6, @CULTURE)
END
SET IDENTITY_INSERT [dbo].[Culture] OFF
--END OF DEFAULT CULTURES
COMMIT