BEGIN TRANSACTION
--START OF DEFAULT BLOG POST STATUSES
SET IDENTITY_INSERT [dbo].[BlogPostStatus] ON
DECLARE @BLOGPPOSTSTATUS_DRAFT NVARCHAR(10)  = 'Draft'
IF NOT EXISTS (SELECT * FROM [dbo].[BlogPostStatus] BPS WHERE [BPS].[Name] = @BLOGPPOSTSTATUS_DRAFT)
BEGIN 
    INSERT INTO [dbo].[BlogPostStatus]([BlogPostStatusId],[Name]) VALUES(1, @BLOGPPOSTSTATUS_DRAFT)
END
DECLARE @BLOGPPOSTSTATUS_PUBLISHED NVARCHAR(10)  = 'Published'
IF NOT EXISTS (SELECT * FROM [dbo].[BlogPostStatus] BPS WHERE [BPS].[Name] = @BLOGPPOSTSTATUS_PUBLISHED)
BEGIN 
    INSERT INTO [dbo].[BlogPostStatus]([BlogPostStatusId],[Name]) VALUES(2, @BLOGPPOSTSTATUS_PUBLISHED)
END
SET IDENTITY_INSERT [dbo].[BlogPostStatus] OFF
--END OF DEFAULT BLOG POST STATUSES
GO
COMMIT