// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NetTopologySuite.Geometries;
using FairPlayCombined.DataAccess.Models.dboSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBlogsSchema;
using FairPlayCombined.DataAccess.Models.FairPlayBudgetSchema;
using FairPlayCombined.DataAccess.Models.FairPlayDatingSchema;
using FairPlayCombined.DataAccess.Models.FairPlayShopSchema;
using FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;
using FairPlayCombined.DataAccess.Models.FairPlayTubeSchema;


namespace FairPlayCombined.DataAccess.Models.FairPlaySocialSchema;

[Table("Post", Schema = "FairPlaySocial")]
public partial class Post
{
    [Key]
    public long PostId { get; set; }

    public int PostVisibilityId { get; set; }

    public long? PhotoId { get; set; }

    public int PostTypeId { get; set; }

    public long? ReplyToPostId { get; set; }

    public long? GroupId { get; set; }

    [Required]
    [StringLength(500)]
    public string Text { get; set; }

    [Required]
    [StringLength(450)]
    public string OwnerApplicationUserId { get; set; }

    public DateTimeOffset RowCreationDateTime { get; set; }

    [Required]
    [StringLength(256)]
    public string RowCreationUser { get; set; }

    [Required]
    [StringLength(250)]
    public string SourceApplication { get; set; }

    [Required]
    [Column("OriginatorIPAddress")]
    [StringLength(100)]
    public string OriginatorIpaddress { get; set; }

    public long? CreatedFromPostId { get; set; }

    public double? CreatedAtLatitude { get; set; }

    public double? CreatedAtLongitude { get; set; }

    public Geometry CreatedAtGeoLocation { get; set; }

    public long? RootPostId { get; set; }

    [ForeignKey("CreatedFromPostId")]
    [InverseProperty("InverseCreatedFromPost")]
    public virtual Post CreatedFromPost { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("Post")]
    public virtual Group Group { get; set; }

    [InverseProperty("CreatedFromPost")]
    public virtual ICollection<Post> InverseCreatedFromPost { get; set; } = new List<Post>();

    [InverseProperty("ReplyToPost")]
    public virtual ICollection<Post> InverseReplyToPost { get; set; } = new List<Post>();

    [InverseProperty("RootPost")]
    public virtual ICollection<Post> InverseRootPost { get; set; } = new List<Post>();

    [ForeignKey("OwnerApplicationUserId")]
    [InverseProperty("Post")]
    public virtual AspNetUsers OwnerApplicationUser { get; set; }

    [ForeignKey("PhotoId")]
    [InverseProperty("Post")]
    public virtual Photo Photo { get; set; }

    [ForeignKey("PostTypeId")]
    [InverseProperty("Post")]
    public virtual PostType PostType { get; set; }

    [ForeignKey("PostVisibilityId")]
    [InverseProperty("Post")]
    public virtual PostVisibility PostVisibility { get; set; }

    [ForeignKey("ReplyToPostId")]
    [InverseProperty("InverseReplyToPost")]
    public virtual Post ReplyToPost { get; set; }

    [ForeignKey("RootPostId")]
    [InverseProperty("InverseRootPost")]
    public virtual Post RootPost { get; set; }
}