// <auto-generated/>
using FairPlayTube.ClientServices.KiotaClient.Account.Logout;
using FairPlayTube.ClientServices.KiotaClient.Account.Manage;
using FairPlayTube.ClientServices.KiotaClient.Account.PerformExternalLogin;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace FairPlayTube.ClientServices.KiotaClient.Account {
    /// <summary>
    /// Builds and executes requests for operations under \Account
    /// </summary>
    public class AccountRequestBuilder : BaseRequestBuilder {
        /// <summary>The Logout property</summary>
        public LogoutRequestBuilder Logout { get =>
            new LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Manage property</summary>
        public ManageRequestBuilder Manage { get =>
            new ManageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PerformExternalLogin property</summary>
        public PerformExternalLoginRequestBuilder PerformExternalLogin { get =>
            new PerformExternalLoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new AccountRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new AccountRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account", rawUrl) {
        }
    }
}
